### PR TITLE
adding quota metrics per project

### PR DESCRIPTION
**Pull request by evkuzin**
This change adds limits metrics for each tenant:
```
curl -s localhost:9180/metrics | grep openstack_nova_quota
# HELP openstack_nova_quota_cores quota_cores
# TYPE openstack_nova_quota_cores gauge
openstack_nova_quota_cores{tenant="admin",type="in_use"} 54
openstack_nova_quota_cores{tenant="admin",type="limit"} 614
openstack_nova_quota_cores{tenant="admin",type="reserved"} 0
# HELP openstack_nova_quota_fixed_ips quota_fixed_ips
# TYPE openstack_nova_quota_fixed_ips gauge
openstack_nova_quota_fixed_ips{tenant="admin",type="in_use"} 0
openstack_nova_quota_fixed_ips{tenant="admin",type="limit"} 0
openstack_nova_quota_fixed_ips{tenant="admin",type="reserved"} 0
# HELP openstack_nova_quota_floating_ips quota_floating_ips
# TYPE openstack_nova_quota_floating_ips gauge
openstack_nova_quota_floating_ips{tenant="admin",type="in_use"} 0
openstack_nova_quota_floating_ips{tenant="admin",type="limit"} 0
openstack_nova_quota_floating_ips{tenant="admin",type="reserved"} 0
# HELP openstack_nova_quota_injected_file_content_bytes quota_injected_file_content_bytes
# TYPE openstack_nova_quota_injected_file_content_bytes gauge
openstack_nova_quota_injected_file_content_bytes{tenant="admin",type="in_use"} 0
openstack_nova_quota_injected_file_content_bytes{tenant="admin",type="limit"} 0
openstack_nova_quota_injected_file_content_bytes{tenant="admin",type="reserved"} 0
# HELP openstack_nova_quota_injected_file_path_bytes quota_injected_file_path_bytes
# TYPE openstack_nova_quota_injected_file_path_bytes gauge
openstack_nova_quota_injected_file_path_bytes{tenant="admin",type="in_use"} 0
openstack_nova_quota_injected_file_path_bytes{tenant="admin",type="limit"} 0
openstack_nova_quota_injected_file_path_bytes{tenant="admin",type="reserved"} 0
# HELP openstack_nova_quota_injected_files quota_injected_files
# TYPE openstack_nova_quota_injected_files gauge
openstack_nova_quota_injected_files{tenant="admin",type="in_use"} 0
openstack_nova_quota_injected_files{tenant="admin",type="limit"} 0
openstack_nova_quota_injected_files{tenant="admin",type="reserved"} 0
# HELP openstack_nova_quota_instances quota_instances
# TYPE openstack_nova_quota_instances gauge
openstack_nova_quota_instances{tenant="admin",type="in_use"} 53
openstack_nova_quota_instances{tenant="admin",type="limit"} 154
openstack_nova_quota_instances{tenant="admin",type="reserved"} 0
# HELP openstack_nova_quota_key_pairs quota_key_pairs
# TYPE openstack_nova_quota_key_pairs gauge
openstack_nova_quota_key_pairs{tenant="admin",type="in_use"} 0
openstack_nova_quota_key_pairs{tenant="admin",type="limit"} 100
openstack_nova_quota_key_pairs{tenant="admin",type="reserved"} 0
# HELP openstack_nova_quota_metadata_items quota_metadata_items
# TYPE openstack_nova_quota_metadata_items gauge
openstack_nova_quota_metadata_items{tenant="admin",type="in_use"} 0
openstack_nova_quota_metadata_items{tenant="admin",type="limit"} 128
openstack_nova_quota_metadata_items{tenant="admin",type="reserved"} 0
# HELP openstack_nova_quota_ram quota_ram
# TYPE openstack_nova_quota_ram gauge
openstack_nova_quota_ram{tenant="admin",type="in_use"} 2.6752e+06
openstack_nova_quota_ram{tenant="admin",type="limit"} 2.2528e+07
openstack_nova_quota_ram{tenant="admin",type="reserved"} 0
# HELP openstack_nova_quota_security_group_rules quota_security_group_rules
# TYPE openstack_nova_quota_security_group_rules gauge
openstack_nova_quota_security_group_rules{tenant="admin",type="in_use"} 0
openstack_nova_quota_security_group_rules{tenant="admin",type="limit"} 0
openstack_nova_quota_security_group_rules{tenant="admin",type="reserved"} 0
# HELP openstack_nova_quota_security_groups quota_security_groups
# TYPE openstack_nova_quota_security_groups gauge
openstack_nova_quota_security_groups{tenant="admin",type="in_use"} 2
openstack_nova_quota_security_groups{tenant="admin",type="limit"} 400
openstack_nova_quota_security_groups{tenant="admin",type="reserved"} 0
# HELP openstack_nova_quota_server_group_members quota_server_group_members
# TYPE openstack_nova_quota_server_group_members gauge
openstack_nova_quota_server_group_members{tenant="admin",type="in_use"} 0
openstack_nova_quota_server_group_members{tenant="admin",type="limit"} 10
openstack_nova_quota_server_group_members{tenant="admin",type="reserved"} 0
# HELP openstack_nova_quota_server_groups quota_server_groups
# TYPE openstack_nova_quota_server_groups gauge
openstack_nova_quota_server_groups{tenant="admin",type="in_use"} 2
openstack_nova_quota_server_groups{tenant="admin",type="limit"} 400
openstack_nova_quota_server_groups{tenant="admin",type="reserved"} 0
```

### CODE REVIEW

**Comment by evkuzin** [comment]
@niedbalski & @alexeymyltsev 
WDYT?

**Comment by yo000** [comment]
Hello, 

Thank you for the patch. We are currently testing it, and had to change "panic(err)" to "return err" as exporter died when target was unreachable.
```
--- exporters/nova.go.ori       2024-01-23 10:39:51.057716000 +0100
+++ exporters/nova.go   2024-01-19 11:43:07.216252000 +0100
@@ -300,7 +300,7 @@
        for _, p := range allProjects {
                quotaSet, err := quotasets.GetDetail(exporter.Client, p.ID).Extract()
                if err != nil {
-                       panic(err)
+                       return err
                }

                ch <- prometheus.MustNewConstMetric(exporter.Metrics["quota_cores"].Metric,
```

**Comment by evkuzin** [comment]
@yo000 Thanks for flagging!
It is indeed supposed to be a `return`. Fixed

**Comment by niedbalski** [comment]
Please fix the conflicts before I can review. Thank you.

**Pull request closed without merging**
