### PR TITLE
Glance api up

### PR DESCRIPTION
**Pull request by parsa97**
This PR based on #252 , and will help to get glance availability without get the entire list of images.

### CODE REVIEW

**Comment by niedbalski** [comment]
Hello @parsa97 can you review the conflicts and add some unit tests that are specific to this patch?

**Review by niedbalski — CHANGES_REQUESTED** [review]
Good change, but needs some fixing in the linter.

**Comment by mitch000001** [comment]
As the mechanism to verify if glance is up is using the import methods enabled does it make sense to also expose those as a metric?

**Comment by niedbalski** [comment]
Please fix the conflicts before I can review. Thank you.

**Pull request closed without merging**
