### PR TITLE
Move stats that are available via Placement API over

### PR DESCRIPTION
**Pull request by StopMotionCuber**
This is a first attempt in order to make some stats from #249 available again. Not really intended to get merged in this state, but to trigger some discussion

Unfortunately, it's not backwards compatible right now, as the name is changed e.g. from `openstack_nova_vcpus_available` to `openstack_placement_vcpus_available` due to the current implementation. But it also wasn't possible to query the information within `nova.go`, as the `exporter.Client` made some assumptions about the microversion, leading to a 404 when doing the queries within that file. I could investigate whether it is possible to give it another prefix than the intended one.

Additionally I'm not sure how the usage is measured for RAM and storage. Is that the actual RAM usage or the allocated RAM usage by VMs? I guess these differ to vCPUs, as they can be overallocated, but not overused

### CODE REVIEW

**Comment by niedbalski** [comment]
@StopMotionCuber I am okay with reviewing this one, as long as you can check the test failures.

**Comment by StopMotionCuber** [comment]
Done so. Do you have an idea how the fixtures were created? These seem outdated to me, as they still contain removed fields from the hypervisor API. I'd prefer to not edit them by hand and get the response somehow from a real world example with a recent version of OpenStack.

Updating these would lead to some test failures where metrics are missing. An even better solution would be to not use fixtures for these but actually fetch this information from a live OpenStack instance, but I haven't set one up myself yet and I don't know what kind of beast it is. Neither did I check how many of the metrics are flaky, something like RAM usage would be flaky for sure

**Comment by frittentheke** [comment]
@niedbalski Regarding the breaking changes of "recent" OpenStack releases this is one of the changes that is required to export certain metrics again.

See my comment at https://github.com/openstack-exporter/openstack-exporter/issues/299#issuecomment-1895524583
I gladly test this if that helps you any in reviewing and merging this.

**Comment by StopMotionCuber** [comment]
As taking a deeper look, my recommendation would actually not be to merge this one (it's kinda hacky) but rather merge https://github.com/openstack-exporter/grafana-dashboards/pull/1. Basically all required metrics are already there, they just have a new name.
You may already use that locally to have a working grafana.

**Comment by frittentheke** [comment]
> As taking a deeper look, my recommendation would actually not be to merge this one (it's kinda hacky) but rather merge [openstack-exporter/grafana-dashboards#1](https://github.com/openstack-exporter/grafana-dashboards/pull/1). Basically all required metrics are already there, they just have a new name. You may already use that locally to have a working grafana.

If all those existing placement metrics already cover all of the missing ones formally fetched from nova (https://github.com/openstack-exporter/openstack-exporter/issues/249#issue-1349067683) that would really slick.

The only thing left would then be to remove the attempts to fetch the metrics from Nova in a recent version of the OpenStack exporter?

**Pull request closed without merging**
