### PR TITLE
exclude volume_status from slow metrics

### PR DESCRIPTION
**Pull request by alexeymyltsev**
https://github.com/openstack-exporter/openstack-exporter/issues/170

### CODE REVIEW

**Comment by niedbalski** [comment]
@alexeymyltsev What's the purpose of this change? Why should we remove volume_status from slow metrics?

**Comment by niedbalski** [comment]
Apologies @alexeymyltsev , that's documented on #170

**Comment by niedbalski** [comment]
@alexeymyltsev CI tests are failing, also .. why not leaving the volume_status in a different function?

**Comment by alexeymyltsev** [comment]
@niedbalski failed build, same fail what was before `sudo snap install go --classic` .
I do not want add separate function because I do not want duplicated calls to API. 
I see it as tradeoff between disabling metrics with one parameter and additional API calls.

**Pull request merged**
