### PR TITLE
Metrics with L3agents for routers

### PR DESCRIPTION
**Pull request by alexeymyltsev**
This PR add metrics with information about l3-agents for router and their HA state for l3-ha routers.
This useful for monitoring problems with HA routers after failover.

### CODE REVIEW

**Comment by alexeymyltsev** [comment]
@niedbalski hello, could you to say what needed for merge this PR?

**Comment by niedbalski** [comment]
@alexeymyltsev LGTM, I'll wait for the CI to come back and merge. Thanks.

**Comment by niedbalski** [comment]
@alexeymyltsev can you check the failed tests and re-submit with the proper fixtures? Thank you

**Comment by alexeymyltsev** [comment]
@niedbalski done

**Pull request merged**
