### PR TITLE
User server supported microversion when nova list services

### PR DESCRIPTION
**Pull request by lrainsun**
When nova cell enabled, we have two nova-conductor service, one is
nova-conductor and another is super nova-super-conductor, they have same
name in different databases (nova_cell0 & nova_cell1).
The only difference for the agent_state metrics is the service ID, but
service ID is actually a db seqNo, they can be same in different
tables. In our cases, we met two nova-conductors have the same label,
that will cause metrics failed to store.
For nova apiversion bigger than 2.53, it will return uuid for service
id, so add microversion for nova client.

### CODE REVIEW

**Comment by lrainsun** [comment]
I'm not sure why test failed with gofmt
I'm already using go version go1.13.15 linux/amd64 for formatting code
@freyes @pborzenkov @mnaser @diurnalist

**Comment by mnaser** [comment]
```
gofmt checking failed!
diff -u ./exporters/exporter_test.go.orig ./exporters/exporter_test.go
--- ./exporters/exporter_test.go.orig	2021-02-07 15:10:30.751246048 +0000
+++ ./exporters/exporter_test.go	2021-02-07 15:10:30.751246048 +0000
@@ -51,15 +51,15 @@
 }
 
 var fixtures map[string]string = map[string]string{
-	"/container-infra/clusters":                                  "container_infra_clusters",
-	"/compute/":                                                  "nova_api_discovery",
-	"/compute/v2.1":                                              "nova_api_v2.1",
-	"/compute/os-services":                                       "nova_os_services",
-	"/compute/os-hypervisors/detail":                             "nova_os_hypervisors",
-	"/compute/flavors/detail":                                    "nova_os_flavors",
-	"/compute/os-availability-zone":                              "nova_os_availability_zones",
-	"/compute/os-security-groups":                                "nova_os_security_groups",
-	"/compute/os-aggregates":                                     "nova_os_aggregates",
+	"/container-infra/clusters":      "container_infra_clusters",
+	"/compute/":                      "nova_api_discovery",
+	"/compute/v2.1":                  "nova_api_v2.1",
+	"/compute/os-services":           "nova_os_services",
+	"/compute/os-hypervisors/detail": "nova_os_hypervisors",
+	"/compute/flavors/detail":        "nova_os_flavors",
+	"/compute/os-availability-zone":  "nova_os_availability_zones",
+	"/compute/os-security-groups":    "nova_os_security_groups",
+	"/compute/os-aggregates":         "nova_os_aggregates",
 	"/compute/limits?tenant_id=0c4e939acacf4376bdcd1129f1a054ad": "nova_os_limits",
 	"/compute/limits?tenant_id=0cbd49cbf76d405d9c86562e1d579bd3": "nova_os_limits",
 	"/compute/limits?tenant_id=2db68fed84324f29bb73130c6c2094fb": "nova_os_limits",

Please ensure you are using go version go1.13.15 linux/amd64 for formatting code.
make: *** [Makefile.common:126: common-style] Error 1
```

**Comment by lrainsun** [comment]
> ```
> gofmt checking failed!
> diff -u ./exporters/exporter_test.go.orig ./exporters/exporter_test.go
> --- ./exporters/exporter_test.go.orig	2021-02-07 15:10:30.751246048 +0000
> +++ ./exporters/exporter_test.go	2021-02-07 15:10:30.751246048 +0000
> @@ -51,15 +51,15 @@
>  }
>  
>  var fixtures map[string]string = map[string]string{
> -	"/container-infra/clusters":                                  "container_infra_clusters",
> -	"/compute/":                                                  "nova_api_discovery",
> -	"/compute/v2.1":                                              "nova_api_v2.1",
> -	"/compute/os-services":                                       "nova_os_services",
> -	"/compute/os-hypervisors/detail":                             "nova_os_hypervisors",
> -	"/compute/flavors/detail":                                    "nova_os_flavors",
> -	"/compute/os-availability-zone":                              "nova_os_availability_zones",
> -	"/compute/os-security-groups":                                "nova_os_security_groups",
> -	"/compute/os-aggregates":                                     "nova_os_aggregates",
> +	"/container-infra/clusters":      "container_infra_clusters",
> +	"/compute/":                      "nova_api_discovery",
> +	"/compute/v2.1":                  "nova_api_v2.1",
> +	"/compute/os-services":           "nova_os_services",
> +	"/compute/os-hypervisors/detail": "nova_os_hypervisors",
> +	"/compute/flavors/detail":        "nova_os_flavors",
> +	"/compute/os-availability-zone":  "nova_os_availability_zones",
> +	"/compute/os-security-groups":    "nova_os_security_groups",
> +	"/compute/os-aggregates":         "nova_os_aggregates",
>  	"/compute/limits?tenant_id=0c4e939acacf4376bdcd1129f1a054ad": "nova_os_limits",
>  	"/compute/limits?tenant_id=0cbd49cbf76d405d9c86562e1d579bd3": "nova_os_limits",
>  	"/compute/limits?tenant_id=2db68fed84324f29bb73130c6c2094fb": "nova_os_limits",
> 
> Please ensure you are using go version go1.13.15 linux/amd64 for formatting code.
> make: *** [Makefile.common:126: common-style] Error 1
> ```

Yes, I saw this. 
But don't know how to fix. 
I've already run gofmt

**Comment by niedbalski** [comment]
LGTM

**Pull request merged**
