### PR TITLE
updating utils.go

### PR DESCRIPTION
**Pull request by mehrdadpfg**
adding identity_interface param to OpenStack exporter

PLEASE wait until gophercloud/utils accepts my pull request in order to parse identity_interface in clouds.yaml file.

### CODE REVIEW

**Comment by niedbalski** [comment]
Hello @mehrdadpfg 

Thank you for taking the time to fix this issue. Could you make sure to run go fmt to avoid this test [0] to fail?

[0] https://circleci.com/gh/openstack-exporter/openstack-exporter/465?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by mehrdadpfg** [comment]
@niedbalski yes sure

**Comment by mehrdadpfg** [comment]
@niedbalski the syntax issue fixed i will check gophercloud/utils to accept pull request to pass the tests here

**Comment by mehrdadpfg** [comment]
@niedbalski have you followed my pull request and answers from @jtopijan ? 
what's your opinion?
changing identity_interface to interface?

**Comment by mehrdadpfg** [comment]
@here @niedbalski ?

**Comment by niedbalski** [comment]
@mehrdadpfg if we consider this pr https://github.com/gophercloud/utils/pull/97/files , this change wouldn't be required, as the default clientconfig will take in consideration the interface, endpoint_type

    interface: "admin"
    endpoint_type: "internal"

**Comment by niedbalski** [comment]
See #65

**Pull request closed without merging**
